import type { BuildAppLayoutInput } from './appLayoutContracts';

export function buildAppLayoutProps({
  activeView,
  handleSwitchView,
  hierarchySection,
  handleSelectHierarchySection,
  displayCells,
  selectedId,
  selectedCell,
  setSelectedId,
  handleOpenCreateCellModal,
  handleHierarchyJump,
  handleOpenExplorerForCell,
  handleOpenAgentCellFileReference,
  handleRevealAgentCellFileReference,
  handleImportAgentCellFileReferences,
  sessionsByCellId,
  activeSessionByCellId,
  sessionActivityByKey,
  terminusProfiles,
  handleSelectSessionFromSidebar,
  createSessionForCell,
  dispatchSessionCommand,
  closeSession,
  detachSession,
  renameSession,
  updateSessionAvatar,
  moveSessionNode,
  prepareSessionContinueOnMobile,
  handleContinueSessionOnMobile,
  projectReady,
  projectError,
  projectRoot,
  recentProjects,
  tmuxStatus,
  handleSelectProjectRoot,
  handleOpenRecentProject,
  actionsScope,
  handleSelectActionsScope,
  handleConfigureProfile,
  appShortcutsScope,
  handleSelectAppShortcutsScope,
  replyQuickPromptsScope,
  handleSelectReplyQuickPromptsScope,
  sessionNamingScope,
  handleSelectSessionNamingScope,
  terminusScopeDisabled,
  terminusSummary,
  appShortcutsScopeDisabled,
  appShortcutsSummary,
  replyQuickPromptsScopeDisabled,
  replyQuickPromptsSummary,
  appShortcutRows,
  replyQuickPromptsRows,
  resolvedReplyQuickPrompts,
  replyQuickPromptsPaths,
  replyQuickPromptsError,
  replyQuickPromptsSaving,
  replyQuickPromptsDirty,
  addReplyQuickPrompt,
  updateReplyQuickPrompt,
  removeReplyQuickPrompt,
  saveReplyQuickPrompts,
  clearReplyQuickPromptsError,
  appShortcutsPaths,
  appShortcutsError,
  appShortcutsSaving,
  appShortcutsDirty,
  updateAppShortcut,
  overrideAppShortcut,
  resetAppShortcut,
  saveAppShortcuts,
  clearAppShortcutsError,
  sessionNamingScopeDisabled,
  sessionNamingSummary,
  sessionNamingSettings,
  resolvedSessionNaming,
  sessionNamingPaths,
  sessionNamingError,
  sessionNamingSaving,
  sessionNamingDirty,
  sessionNamingPreviewContext,
  updateSessionNamingRule,
  updateSessionNamingList,
  renameSessionNamingList,
  removeSessionNamingList,
  addSessionNamingList,
  saveSessionNamingSettings,
  clearSessionNamingError,
  profileRows,
  activeProfileId,
  projectSettingsPath,
  agentSettingsPath,
  terminusError,
  terminusSaving,
  terminusDirty,
  addProfile,
  removeProfile,
  overrideProfile,
  resetProfile,
  updateProfile,
  saveTerminusSettings,
  bindingRowsByProfile,
  addBinding,
  removeBinding,
  overrideBinding,
  resetBinding,
  updateBinding,
  clearTerminusError,
  gateScope,
  handleSelectGateScope,
  gateStage,
  setGateStage,
  gateScopeDisabled,
  gateSummary,
  gateRows,
  projectGatesPath,
  agentGatesPath,
  gatesError,
  gatesSaving,
  addGate,
  removeGate,
  overrideGate,
  resetGate,
  updateGate,
  handleSaveGates,
  worktreeLinks,
  worktreeLinksAuto,
  worktreeLinksCandidates,
  worktreeLinksStatusesByPath,
  worktreeLinksConfigPath,
  worktreeLinksLoading,
  worktreeLinksError,
  worktreeLinksDirty,
  toggleWorktreeLinksAuto,
  addWorktreeLink,
  addWorktreeLinkFromCandidate,
  updateWorktreeLink,
  removeWorktreeLink,
  applyWorktreeLink,
  applyAllWorktreeLinks,
  saveWorktreeLinks,
  refreshWorktreeLinks,
  resolvedRepoRoot,
  canUseScopedConfig,
  editorPaneProps,
  sidebarWidth,
  sidebarCollapsed,
  setSidebarWidth,
  handleSidebarResizeEnd,
  handleToggleSidebar,
  hilDrawerOpen,
  hilDrawerPanel,
  setHilDrawerOpen,
  handleSelectHilDrawerPanel,
  openPromoteModal,
  hilCommentsProps,
  hilDraftsProps,
  hilReplyProps,
  memoDrawerProps,
  appLayoutActionSheetsProps,
  appLayoutExplorerSidebarProps,
  appLayoutExplorerPaneProps,
  appLayoutMemoPaneProps,
  appLayoutMemoSidebarProps,
}: BuildAppLayoutInput) {
  return {
    activeView,
    onSwitchView: handleSwitchView,
    hierarchySection,
    onSelectHierarchySection: handleSelectHierarchySection,
    cells: displayCells,
    selectedId,
    selectedCell,
    onSelectCell: setSelectedId,
    onCreateCell: handleOpenCreateCellModal,
    onJumpToHierarchy: handleHierarchyJump,
    onOpenExplorerForCell: handleOpenExplorerForCell,
    onOpenAgentCellFileReference: handleOpenAgentCellFileReference,
    onRevealAgentCellFileReference: handleRevealAgentCellFileReference,
    onImportAgentCellFileReferences: handleImportAgentCellFileReferences,
    sessionsByCellId,
    activeSessionByCellId,
    sessionActivityByKey,
    terminusProfiles,
    onSelectSession: handleSelectSessionFromSidebar,
    onCreateSession: createSessionForCell,
    onDispatchSessionCommand: dispatchSessionCommand,
    onCloseSession: closeSession,
    onDetachSession: detachSession,
    onRenameSession: renameSession,
    onUpdateSessionAvatar: updateSessionAvatar,
    onMoveSessionNode: moveSessionNode,
    onContinueSessionOnMobile:
      handleContinueSessionOnMobile || prepareSessionContinueOnMobile,
    projectReady,
    projectError,
    projectRoot,
    recentProjects,
    tmuxStatus,
    onSelectProject: handleSelectProjectRoot,
    onOpenRecentProject: handleOpenRecentProject,
    onOpenActions: () => handleHierarchyJump('actions'),
    onOpenAppShortcuts: () => handleHierarchyJump('app-shortcuts'),
    onOpenReplyQuickPrompts: () => handleHierarchyJump('reply-quick-prompts'),
    onOpenGates: () => handleHierarchyJump('gates'),
    onOpenSoftlinks: () => handleHierarchyJump('softlinks'),
    actionsScope,
    onSelectActionsScope: handleSelectActionsScope,
    onConfigureProfile: handleConfigureProfile,
    appShortcutsScope,
    onSelectAppShortcutsScope: handleSelectAppShortcutsScope,
    replyQuickPromptsScope,
    onSelectReplyQuickPromptsScope: handleSelectReplyQuickPromptsScope,
    sessionNamingScope,
    onSelectSessionNamingScope: handleSelectSessionNamingScope,
    actionsScopeDisabled: terminusScopeDisabled,
    actionSummary: terminusSummary,
    appShortcutsScopeDisabled,
    appShortcutsSummary,
    replyQuickPromptsScopeDisabled,
    replyQuickPromptsSummary,
    appShortcutRows,
    replyQuickPromptsRows,
    resolvedReplyQuickPrompts,
    replyQuickPromptsPaths,
    replyQuickPromptsError,
    replyQuickPromptsSaving,
    replyQuickPromptsDirty,
    onAddReplyQuickPrompt: addReplyQuickPrompt,
    onUpdateReplyQuickPrompt: updateReplyQuickPrompt,
    onRemoveReplyQuickPrompt: removeReplyQuickPrompt,
    onSaveReplyQuickPrompts: saveReplyQuickPrompts,
    onClearReplyQuickPromptsError: clearReplyQuickPromptsError,
    appShortcutsPaths,
    appShortcutsError,
    appShortcutsSaving,
    appShortcutsDirty,
    onUpdateAppShortcut: updateAppShortcut,
    onOverrideAppShortcut: overrideAppShortcut,
    onResetAppShortcut: resetAppShortcut,
    onSaveAppShortcuts: saveAppShortcuts,
    onClearAppShortcutsError: clearAppShortcutsError,
    sessionNamingScopeDisabled,
    sessionNamingSummary,
    sessionNamingSettings,
    resolvedSessionNaming,
    sessionNamingPaths,
    sessionNamingError,
    sessionNamingSaving,
    sessionNamingDirty,
    sessionNamingPreviewContext,
    onUpdateSessionNamingRule: updateSessionNamingRule,
    onUpdateSessionNamingList: updateSessionNamingList,
    onRenameSessionNamingList: renameSessionNamingList,
    onRemoveSessionNamingList: removeSessionNamingList,
    onAddSessionNamingList: addSessionNamingList,
    onSaveSessionNaming: saveSessionNamingSettings,
    onClearSessionNamingError: clearSessionNamingError,
    actionsRows: profileRows,
    activeProfileId,
    projectActionsPath: projectSettingsPath,
    agentActionsPath: agentSettingsPath,
    quickActionsError: terminusError,
    quickActionsSaving: terminusSaving,
    quickActionsDirty: terminusDirty,
    onAddAction: addProfile,
    onRemoveAction: removeProfile,
    onOverrideAction: overrideProfile,
    onResetAction: resetProfile,
    onUpdateAction: updateProfile,
    onSaveActions: saveTerminusSettings,
    bindingsByProfile: bindingRowsByProfile,
    onAddBinding: addBinding,
    onRemoveBinding: removeBinding,
    onOverrideBinding: overrideBinding,
    onResetBinding: resetBinding,
    onUpdateBinding: updateBinding,
    onClearTerminusError: clearTerminusError,
    gateScope,
    onSelectGateScope: handleSelectGateScope,
    gateStage,
    onSelectGateStage: setGateStage,
    gateScopeDisabled,
    gateSummary,
    gateRows,
    projectGatesPath,
    agentGatesPath,
    gatesError,
    gatesSaving,
    onAddGate: addGate,
    onRemoveGate: removeGate,
    onOverrideGate: overrideGate,
    onResetGate: resetGate,
    onUpdateGate: updateGate,
    onSaveGates: handleSaveGates,
    worktreeLinks,
    worktreeLinksAuto,
    worktreeLinksCandidates,
    worktreeLinksStatusesByPath,
    worktreeLinksConfigPath,
    worktreeLinksLoading,
    worktreeLinksError,
    worktreeLinksDirty,
    onToggleWorktreeLinksAuto: toggleWorktreeLinksAuto,
    onAddWorktreeLink: addWorktreeLink,
    onAddWorktreeLinkFromCandidate: addWorktreeLinkFromCandidate,
    onUpdateWorktreeLink: updateWorktreeLink,
    onRemoveWorktreeLink: removeWorktreeLink,
    onApplyWorktreeLink: applyWorktreeLink,
    onApplyAllWorktreeLinks: applyAllWorktreeLinks,
    onSaveWorktreeLinks: saveWorktreeLinks,
    onRefreshWorktreeLinks: refreshWorktreeLinks,
    repoRoot: resolvedRepoRoot,
    canUseProjectScope: canUseScopedConfig,
    canUseAgentScope: canUseScopedConfig,
    editorPaneProps,
    sidebarWidth,
    sidebarCollapsed,
    onResizeSidebar: setSidebarWidth,
    onResizeSidebarEnd: handleSidebarResizeEnd,
    onToggleSidebar: handleToggleSidebar,
    hilDrawerOpen,
    hilDrawerPanel,
    onToggleHilDrawer: setHilDrawerOpen,
    onSelectHilDrawerPanel: handleSelectHilDrawerPanel,
    onOpenHilPromote: openPromoteModal,
    hilCommentsProps,
    hilDraftsProps,
    hilReplyProps,
    memoDrawerProps,
    actionSheetsProps: appLayoutActionSheetsProps,
    explorerSidebarProps: appLayoutExplorerSidebarProps,
    explorerPaneProps: appLayoutExplorerPaneProps,
    memoPaneProps: appLayoutMemoPaneProps,
    memoSidebarProps: appLayoutMemoSidebarProps,
  };
}

export type AppLayoutProps = ReturnType<typeof buildAppLayoutProps>;
