export function buildAppLayoutPanelProps({
  selectedCell,
  projectRoot,
  activeSession,
  activeReplySelection,
  replyFocusToken,
  resolvedReplyQuickPrompts,
  sessionTargets,
  handleClearReplySelection,
  sendSessionText,
  handleJumpToSession,
  activeTab,
  cursorPosition,
  comments,
  commentsLoading,
  commentsError,
  handleOpenMemoReference,
  handleRevealMemoReference,
  openCommentModal,
  updateCommentStatus,
  commentModalOpen,
  commentTarget,
  commentMessage,
  commentTodo,
  commentError,
  commentSaving,
  commentSnippet,
  commentSnippetLoading,
  commentSnippetError,
  setCommentMessage,
  setCommentTodo,
  closeCommentModal,
  submitComment,
  promoteModalOpen,
  promoteDescription,
  promoteError,
  promoteLoading,
  promoteItems,
  promoteSelectedIds,
  promotePreviewById,
  promoteStep,
  promoteDraft,
  promoteMode,
  promoteActionSheet,
  promoteGateStatus,
  promoteExecutionStatus,
  promoteSessionId,
  sessions,
  sessionActivityByKey,
  closePromoteModal,
  setPromoteDescription,
  togglePromoteItem,
  togglePromoteGroup,
  loadPromotePreview,
  setPromoteSessionId,
  selectPromoteMode,
  createPromoteSession,
  dispatchPromote,
  confirmPromote,
  handleFocusPromoteSession,
  handleOpenDeliveryTimeline,
  promoteDraftId,
  promoteActionSheetId,
  handleDispatchActionSheet,
  cancelActionSheet,
  handleArchiveActionSheet,
  handleDeleteActionSheet,
  handleOpenActionSheets,
  hilMemo,
  handleOpenMemoDraft,
  handleViewActionSheetSession,
  handleRunDraftInActiveSession,
  actionSheets,
  activeSessionId,
  handleOpenMemoInbox,
  handleFocusInboxInput,
  memoCapture,
  memoVoiceShortcut,
  screenshotShortcut,
  projectReady,
  projectError,
  handleSelectProjectRoot,
  handleCreateDraftActionSheet,
  memoFocusTarget,
  handleFocusInboxInputHandled,
  setShowArchivedActionSheets,
  actionSheetDetail,
  actionSheetId,
  setActionSheetId,
  handleCreateActionSheet,
  handleSaveActionSheet,
  updateActionSheetChecks,
  refreshActionSheets,
  showArchivedActionSheets,
  refreshActionSheetChecks,
  handleViewActionSheetSession: viewActionSheetSession,
  availableActionSessions,
  actionSheetSessionId,
  setActionSheetSessionId,
  actionSheetsLoading,
  actionSheetDetailLoading,
  actionSheetInlineError,
  actionSheetsError,
  explorerRootPath,
  explorerRootLabel,
  cells,
  selectedId,
  setSelectedId,
  sessionMapOpen,
  handleSwitchView,
  explorerMeta,
  handleDispatchExplorerFeed,
  explorerDeliverySummary,
  handleOpenExplorerDeliveryTimeline,
  handleToggleSessionMap,
  pendingExplorerReveal,
  setPendingExplorerReveal,
  workbench,
  handleAddCommentFromExplorer,
  hilCommentCounts,
  handleJumpToComments,
  commentLines,
  handleWorkbenchMetaChange,
  setCursorPosition,
  handleWorkbenchSelectionChange,
  pendingWorkbenchJump,
  setPendingWorkbenchJump,
  handleRevealPathInExplorerFromWorkbench,
}: any) {
  const hilReplyProps = {
    cell: selectedCell,
    session: activeSession,
    worktreePath: selectedCell?.attachedWorktreePath || projectRoot || '',
    selection: activeReplySelection,
    focusToken: replyFocusToken,
    resolvedQuickPrompts: resolvedReplyQuickPrompts,
    sessionTargets,
    onClearSelection: handleClearReplySelection,
    onSendSessionText: sendSessionText,
    onJumpToSession: handleJumpToSession,
  };

  const hilCommentsProps = {
    activeFile: activeTab?.path || '',
    cursorPosition,
    worktreePath: selectedCell?.attachedWorktreePath || projectRoot || '',
    comments,
    loading: commentsLoading,
    error: commentsError,
    onOpenAnchor: ({ path, line, column }: { path?: string; line?: number; column?: number } = {}) =>
      handleOpenMemoReference({
        path,
        line,
        column,
        sourceSurface: 'memo',
      }),
    onRevealAnchor: ({ path }: { path?: string } = {}) =>
      handleRevealMemoReference({
        path,
        sourceSurface: 'memo',
      }),
    onOpenComment: openCommentModal,
    onUpdateStatus: updateCommentStatus,
    commentModalOpen,
    commentTarget,
    commentMessage,
    commentTodo,
    commentError,
    commentSaving,
    commentSnippet,
    commentSnippetLoading,
    commentSnippetError,
    onCommentMessageChange: setCommentMessage,
    onCommentTodoChange: setCommentTodo,
    onCloseComment: closeCommentModal,
    onSubmitComment: submitComment,
    promoteModalOpen,
    promoteDescription,
    promoteError,
    promoteLoading,
    promoteItems,
    promoteSelectedIds,
    promotePreviewById,
    promoteStep,
    promoteDraft,
    promoteMode,
    promoteActionSheet,
    promoteGateStatus,
    promoteExecutionStatus,
    promoteSessionId,
    sessions,
    sessionActivityByKey,
    selectedCellId: selectedCell?.id || '',
    onClosePromote: closePromoteModal,
    onPromoteDescriptionChange: setPromoteDescription,
    onTogglePromoteItem: togglePromoteItem,
    onTogglePromoteGroup: togglePromoteGroup,
    onPromotePreview: loadPromotePreview,
    onSelectPromoteSession: setPromoteSessionId,
    onSelectPromoteMode: selectPromoteMode,
    onCreatePromoteSession: createPromoteSession,
    onDispatchPromote: dispatchPromote,
    onConfirmPromote: confirmPromote,
    onFocusPromoteSession: handleFocusPromoteSession,
    onOpenPromoteTimeline: () =>
      handleOpenDeliveryTimeline({
        draftId: promoteDraftId,
        actionSheetId: promoteActionSheetId,
      }),
    onDispatchActionSheet: handleDispatchActionSheet,
    onCancelActionSheet: cancelActionSheet,
    onArchiveActionSheet: handleArchiveActionSheet,
    onDeleteActionSheet: handleDeleteActionSheet,
    onOpenActionSheets: handleOpenActionSheets,
  };

  const hilDraftsProps = {
    drafts: hilMemo.draftItems,
    summarizeBody: hilMemo.summarizeBody,
    onOpenDraft: handleOpenMemoDraft,
    onViewSession: handleViewActionSheetSession,
    onRunDraft: handleRunDraftInActiveSession,
    actionSheets,
    sessions,
    activeSessionId,
  };

  const memoDrawerProps = {
    activeInboxId: hilMemo.activeInboxSection?.id || 'comments',
    onSelectInbox: handleOpenMemoInbox,
    onOpenInbox: () => handleOpenMemoInbox('comments'),
    onFocusInboxInput: handleFocusInboxInput,
    flashValue: memoCapture.flashText,
    onFlashChange: memoCapture.onFlashChange,
    onSaveFlash: memoCapture.handleCreateFlash,
    flashVoice: memoCapture.flashVoice,
    flashVoiceSegments: memoCapture.flashVoiceSegments,
    flashVoiceShortcut: memoVoiceShortcut,
    excerptUrl: memoCapture.excerptUrl,
    onExcerptUrlChange: memoCapture.setExcerptUrl,
    onFetchExcerpt: memoCapture.handleFetchExcerpt,
    excerptPreview: memoCapture.excerptPreview,
    excerptFetching: memoCapture.excerptFetching,
    excerptNote: memoCapture.excerptNote,
    onExcerptNoteChange: memoCapture.setExcerptNote,
    onSaveExcerpt: memoCapture.handleCreateExcerpt,
    screenshotAsset: memoCapture.screenshotAsset,
    pendingCapture: memoCapture.captureResult,
    screenshotNote: memoCapture.screenshotNote,
    onScreenshotNoteChange: memoCapture.setScreenshotNote,
    onCaptureScreenshot: memoCapture.handleCaptureScreenshot,
    onOpenRouting: memoCapture.handleOpenRouting,
    captureLoading: memoCapture.captureLoading,
    screenshotShortcut,
  };

  const appLayoutActionSheetsProps = {
    projectReady,
    projectError,
    onSelectProject: handleSelectProjectRoot,
    sheets: actionSheets,
    selectedSheet: actionSheetDetail,
    selectedId: actionSheetId,
    onSelectSheet: setActionSheetId,
    onCreateSheet: handleCreateActionSheet,
    onSaveSheet: handleSaveActionSheet,
    onUpdateChecks: updateActionSheetChecks,
    onRefreshList: refreshActionSheets,
    showArchived: showArchivedActionSheets,
    onToggleArchived: () => setShowArchivedActionSheets((value: boolean) => !value),
    onRefreshChecks: refreshActionSheetChecks,
    onDispatchSheet: handleDispatchActionSheet,
    onCancelSheet: cancelActionSheet,
    onArchiveSheet: handleArchiveActionSheet,
    onDeleteSheet: handleDeleteActionSheet,
    onViewSession: viewActionSheetSession,
    sessions: availableActionSessions,
    sessionId: actionSheetSessionId,
    onSelectSession: setActionSheetSessionId,
    loading: actionSheetsLoading,
    detailLoading: actionSheetDetailLoading,
    error: actionSheetInlineError || actionSheetsError,
  };

  const appLayoutExplorerSidebarProps = {
    rootPath: explorerRootPath,
    rootLabel: explorerRootLabel,
    cells: projectReady ? cells : [],
    selectedId,
    onSelectCell: setSelectedId,
    selectedCell,
    sessions,
    activeSessionId,
    sessionActivityByKey,
    onJumpToAgents: () => handleSwitchView('agent-cells'),
    workbenchMeta: explorerMeta,
    onDispatchFeed: handleDispatchExplorerFeed,
    explorerDeliverySummary,
    onOpenDeliveryTimeline: handleOpenExplorerDeliveryTimeline,
    onToggleSessionMap: handleToggleSessionMap,
    sessionMapOpen,
    revealRequest: pendingExplorerReveal,
    onRevealHandled: () => setPendingExplorerReveal(null),
    onOpenFile: ({ path, mode }: { path: string; mode: string }) => {
      workbench.openFile({
        path,
        mode,
        rootPath: explorerRootPath,
        cellId: selectedCell?.id || undefined,
      });
    },
    onLaunchWebResearchUrl: async (url: string) => {
      workbench.openBoundedWebResearch({
        url,
        rootPath: explorerRootPath,
        cellId: selectedCell?.id || undefined,
      });
    },
    onAddComment: handleAddCommentFromExplorer,
    commentCountsByPath: hilCommentCounts,
    onJumpToComments: handleJumpToComments,
  };

  const appLayoutExplorerPaneProps = {
    workbench,
    activeRootPath: explorerRootPath,
    activeRootLabel: explorerRootLabel,
    projectReady,
    projectError,
    onSelectProject: handleSelectProjectRoot,
    cellId: selectedCell?.id || 'repo',
    onTabMetaChange: handleWorkbenchMetaChange,
    commentLines,
    onOpenComment: openCommentModal,
    onCursorPositionChange: setCursorPosition,
    onSelectionChange: handleWorkbenchSelectionChange,
    pendingJump: pendingWorkbenchJump,
    onJumpHandled: () => setPendingWorkbenchJump(null),
    onRevealPathInExplorer: handleRevealPathInExplorerFromWorkbench,
  };

  const appLayoutMemoPaneProps = {
    ...hilMemo,
    ...memoCapture,
    flashVoiceShortcut: memoVoiceShortcut,
    screenshotShortcut,
    worktreePath: selectedCell?.attachedWorktreePath || projectRoot || '',
    projectRoot,
    selectedCellId: selectedCell?.id || '',
    projectReady,
    projectError,
    onSelectProject: handleSelectProjectRoot,
    onOpenReference: ({
      path,
      line,
      column,
    }: {
      path?: string;
      line?: number;
      column?: number;
    } = {}) =>
      handleOpenMemoReference({
        path,
        line,
        column,
        sourceSurface: 'memo',
      }),
    onRevealReference: ({ path }: { path?: string } = {}) =>
      handleRevealMemoReference({
        path,
        sourceSurface: 'memo',
      }),
    sessions,
    onViewSession: handleViewActionSheetSession,
    actionSheets,
    onDispatchActionSheet: handleDispatchActionSheet,
    onCancelActionSheet: cancelActionSheet,
    onArchiveActionSheet: handleArchiveActionSheet,
    onDeleteActionSheet: handleDeleteActionSheet,
    onOpenActionSheets: handleOpenActionSheets,
    onCreateActionSheet: handleCreateDraftActionSheet,
    focusInboxInputId: memoFocusTarget,
    onFocusInboxInputHandled: handleFocusInboxInputHandled,
  };

  const appLayoutMemoSidebarProps = {
    ...hilMemo,
    projectReady,
  };

  return {
    hilReplyProps,
    hilCommentsProps,
    hilDraftsProps,
    memoDrawerProps,
    appLayoutActionSheetsProps,
    appLayoutExplorerSidebarProps,
    appLayoutExplorerPaneProps,
    appLayoutMemoPaneProps,
    appLayoutMemoSidebarProps,
  };
}
