import { buildAppLayoutPanelProps } from './buildAppLayoutPanelProps';
import { buildAppLayoutProps } from './buildAppLayoutProps';

export function buildComposedAppLayoutProps({
  layoutState,
  projectState,
  scopeState,
  gateState,
  sessionsState,
  sessionReplyContext,
  hierarchyConfig,
  promoteWorkflow,
  hilCommentState,
  actionSheetsState,
  workbenchState,
  selectionState,
  memoState,
  navigationHandlers,
  actionHandlers,
  explorerState,
}: any) {
  const editorPaneProps = {
    cell: layoutState.selectedCell,
    projectReady: projectState.projectReady,
    projectError: projectState.projectError,
    terminalMode: layoutState.terminalMode,
    terminalOpen: layoutState.terminalOpen,
    sessionId: sessionsState.activeSessionId,
    sessionTargets: selectionState.sessionTargets,
    sessions: sessionsState.sessions,
    sessionLoading: sessionsState.sessionLoading,
    sessionError: sessionsState.sessionError,
    terminusBindings: sessionReplyContext.activeProfileBindings,
    tmuxStatus: projectState.tmuxStatus,
    gateResultsByStage: gateState.gateResultsByStage,
    gatesCheckingByStage: gateState.gatesCheckingByStage,
    gateDisplayStage: gateState.gateDisplayStage,
    idleSince: sessionsState.lastActivityAt,
    isVisible: layoutState.activeView === 'agent-cells',
    onRefreshSessions: sessionsState.refreshSessions,
    onStateChange: actionHandlers.handleStateChange,
    onTurnGateCreate: actionHandlers.handleTurnGateCreateSheet,
    onTurnGateExecute: actionHandlers.handleTurnGateExecuteSheet,
    onOpenTerminal: actionHandlers.handleOpenTerminal,
    onZoomIn: sessionsState.zoomIn,
    onZoomOut: sessionsState.zoomOut,
    onZoomReset: sessionsState.zoomReset,
    onSelectProject: navigationHandlers.handleSelectProjectRoot,
    pendingCommand: sessionsState.pendingCommand,
    onCommandSent: sessionsState.acknowledgeCommandSent,
    onSessionActivity: sessionsState.updateSessionActivity,
    onSessionAttached: sessionsState.handleSessionAttached,
    onSendSessionText: sessionsState.sendSessionText,
    terminalFontSize: sessionsState.activeFontSize,
    onUpdateCellAvatar: actionHandlers.handleUpdateCellAvatar,
    onOpenWorkbenchFile: actionHandlers.handleOpenWorkbenchFile,
    onJumpToSession: sessionReplyContext.handleJumpToSession,
    onJumpToMemo: sessionReplyContext.handleJumpToReplyMemo,
    activityDiffThreshold: gateState.activityDiffThreshold,
    onSelectionContext: actionHandlers.handleSelectionContext,
    onReplySelection: actionHandlers.handleReplySelection,
  };

  const {
    hilReplyProps,
    hilCommentsProps,
    hilDraftsProps,
    memoDrawerProps,
    appLayoutActionSheetsProps,
    appLayoutExplorerSidebarProps,
    appLayoutExplorerPaneProps,
    appLayoutMemoPaneProps,
    appLayoutMemoSidebarProps,
  } = buildAppLayoutPanelProps({
    selectedCell: layoutState.selectedCell,
    projectRoot: projectState.projectRoot,
    ...sessionsState,
    ...hierarchyConfig,
    ...sessionReplyContext,
    activeSession: sessionReplyContext.activeSession,
    activeReplySelection: sessionReplyContext.activeReplySelection,
    replyFocusToken: selectionState.replyFocusToken,
    sessionTargets: selectionState.sessionTargets,
    handleClearReplySelection: sessionReplyContext.handleClearReplySelection,
    handleJumpToSession: sessionReplyContext.handleJumpToSession,
    handleJumpToReplyMemo: sessionReplyContext.handleJumpToReplyMemo,
    activeTab: workbenchState.activeTab,
    cursorPosition: workbenchState.cursorPosition,
    ...hilCommentState,
    handleOpenMemoReference: actionHandlers.handleOpenMemoReference,
    handleRevealMemoReference: actionHandlers.handleRevealMemoReference,
    ...promoteWorkflow,
    handleFocusPromoteSession: actionHandlers.handleFocusPromoteSession,
    handleOpenDeliveryTimeline: actionHandlers.handleOpenDeliveryTimeline,
    handleDispatchActionSheet: actionHandlers.handleDispatchActionSheet,
    cancelActionSheet: actionSheetsState.cancelSheet,
    handleArchiveActionSheet: actionHandlers.handleArchiveActionSheet,
    handleDeleteActionSheet: actionHandlers.handleDeleteActionSheet,
    handleOpenActionSheets: actionHandlers.handleOpenActionSheets,
    hilMemo: memoState.hilMemo,
    handleOpenMemoDraft: actionHandlers.handleOpenMemoDraft,
    handleViewActionSheetSession: actionHandlers.handleViewActionSheetSession,
    handleRunDraftInActiveSession: actionHandlers.handleRunDraftInActiveSession,
    actionSheets: actionSheetsState.sheets,
    handleOpenMemoInbox: actionHandlers.handleOpenMemoInbox,
    handleFocusInboxInput: actionHandlers.handleFocusInboxInput,
    memoCapture: memoState.memoCapture,
    projectReady: projectState.projectReady,
    projectError: projectState.projectError,
    handleSelectProjectRoot: navigationHandlers.handleSelectProjectRoot,
    handleCreateDraftActionSheet: actionHandlers.handleCreateDraftActionSheet,
    memoFocusTarget: memoState.memoFocusTarget,
    handleFocusInboxInputHandled: actionHandlers.handleFocusInboxInputHandled,
    setShowArchivedActionSheets: actionSheetsState.setShowArchived,
    actionSheetDetail: actionSheetsState.selectedSheet,
    actionSheetId: actionSheetsState.selectedId,
    setActionSheetId: actionSheetsState.setSelectedId,
    handleCreateActionSheet: actionHandlers.handleCreateActionSheet,
    handleSaveActionSheet: actionHandlers.handleSaveActionSheet,
    updateActionSheetChecks: actionSheetsState.updateSheetChecks,
    refreshActionSheets: actionSheetsState.refreshList,
    showArchivedActionSheets: actionSheetsState.showArchived,
    refreshActionSheetChecks: actionSheetsState.refreshChecks,
    availableActionSessions: selectionState.availableActionSessions,
    actionSheetSessionId: selectionState.actionSheetSessionId,
    setActionSheetSessionId: actionHandlers.setActionSheetSessionId,
    actionSheetsLoading: actionSheetsState.loading,
    actionSheetDetailLoading: actionSheetsState.detailLoading,
    actionSheetInlineError: selectionState.actionSheetInlineError,
    actionSheetsError: actionSheetsState.error,
    explorerRootPath: explorerState.explorerRootPath,
    explorerRootLabel: explorerState.explorerRootLabel,
    cells: selectionState.cells,
    selectedId: layoutState.selectedId,
    setSelectedId: selectionState.setSelectedId,
    sessionMapOpen: explorerState.sessionMapOpen,
    handleSwitchView: navigationHandlers.handleSwitchView,
    explorerMeta: selectionState.explorerMeta,
    handleDispatchExplorerFeed: actionHandlers.handleDispatchExplorerFeed,
    explorerDeliverySummary: explorerState.explorerDeliverySummary,
    handleOpenExplorerDeliveryTimeline: actionHandlers.handleOpenExplorerDeliveryTimeline,
    handleToggleSessionMap: actionHandlers.handleToggleSessionMap,
    pendingExplorerReveal: selectionState.pendingExplorerReveal,
    setPendingExplorerReveal: actionHandlers.setPendingExplorerReveal,
    workbench: workbenchState.workbench,
    handleAddCommentFromExplorer: actionHandlers.handleAddCommentFromExplorer,
    hilCommentCounts: hilCommentState.commentCountsByPath,
    handleJumpToComments: actionHandlers.handleJumpToComments,
    commentLines: hilCommentState.commentLines,
    handleWorkbenchMetaChange: actionHandlers.handleWorkbenchMetaChange,
    setCursorPosition: workbenchState.setCursorPosition,
    handleWorkbenchSelectionChange: actionHandlers.handleWorkbenchSelectionChange,
    pendingWorkbenchJump: selectionState.pendingWorkbenchJump,
    setPendingWorkbenchJump: actionHandlers.setPendingWorkbenchJump,
    handleRevealPathInExplorerFromWorkbench: actionHandlers.handleRevealPathInExplorerFromWorkbench,
  });

  return buildAppLayoutProps({
    activeView: layoutState.activeView,
    handleSwitchView: navigationHandlers.handleSwitchView,
    hierarchySection: layoutState.hierarchySection,
    handleSelectHierarchySection: navigationHandlers.handleSelectHierarchySection,
    displayCells: layoutState.displayCells,
    selectedId: layoutState.selectedId,
    selectedCell: layoutState.selectedCell,
    setSelectedId: selectionState.setSelectedId,
    handleOpenCreateCellModal: actionHandlers.handleOpenCreateCellModal,
    handleHierarchyJump: navigationHandlers.handleHierarchyJump,
    handleOpenExplorerForCell: actionHandlers.handleOpenExplorerForCell,
    handleOpenAgentCellFileReference: actionHandlers.handleOpenAgentCellFileReference,
    handleRevealAgentCellFileReference: actionHandlers.handleRevealAgentCellFileReference,
    handleImportAgentCellFileReferences: actionHandlers.handleImportAgentCellFileReferences,
    handleContinueSessionOnMobile: actionHandlers.handleContinueSessionOnMobile,
    ...sessionsState,
    terminusProfiles: sessionReplyContext.terminusProfiles,
    handleSelectSessionFromSidebar: navigationHandlers.handleSelectSessionFromSidebar,
    projectReady: projectState.projectReady,
    projectError: projectState.projectError,
    projectRoot: projectState.projectRoot,
    recentProjects: projectState.recentProjects,
    tmuxStatus: projectState.tmuxStatus,
    handleSelectProjectRoot: navigationHandlers.handleSelectProjectRoot,
    handleOpenRecentProject: navigationHandlers.handleOpenRecentProject,
    actionsScope: scopeState.actionsScope,
    handleSelectActionsScope: navigationHandlers.handleSelectActionsScope,
    handleConfigureProfile: navigationHandlers.handleConfigureProfile,
    appShortcutsScope: scopeState.appShortcutsScope,
    handleSelectAppShortcutsScope: navigationHandlers.handleSelectAppShortcutsScope,
    replyQuickPromptsScope: scopeState.replyQuickPromptsScope,
    handleSelectReplyQuickPromptsScope: navigationHandlers.handleSelectReplyQuickPromptsScope,
    sessionNamingScope: scopeState.sessionNamingScope,
    handleSelectSessionNamingScope: navigationHandlers.handleSelectSessionNamingScope,
    ...hierarchyConfig,
    sessionNamingPreviewContext: sessionReplyContext.sessionNamingPreviewContext,
    gateScope: scopeState.gateScope,
    handleSelectGateScope: navigationHandlers.handleSelectGateScope,
    gateStage: scopeState.gateStage,
    setGateStage: navigationHandlers.setGateStage,
    handleSaveGates: navigationHandlers.handleSaveGates,
    editorPaneProps,
    sidebarWidth: layoutState.sidebarWidth,
    sidebarCollapsed: layoutState.sidebarCollapsed,
    setSidebarWidth: navigationHandlers.setSidebarWidth,
    handleSidebarResizeEnd: navigationHandlers.handleSidebarResizeEnd,
    handleToggleSidebar: navigationHandlers.handleToggleSidebar,
    hilDrawerOpen: layoutState.hilDrawerOpen,
    hilDrawerPanel: layoutState.hilDrawerPanel,
    setHilDrawerOpen: navigationHandlers.setHilDrawerOpen,
    handleSelectHilDrawerPanel: navigationHandlers.handleSelectHilDrawerPanel,
    openPromoteModal: promoteWorkflow.openPromoteModal,
    hilCommentsProps,
    hilDraftsProps,
    hilReplyProps,
    memoDrawerProps,
    appLayoutActionSheetsProps,
    appLayoutExplorerSidebarProps,
    appLayoutExplorerPaneProps,
    appLayoutMemoPaneProps,
    appLayoutMemoSidebarProps,
  });
}
